# Generated by Django 4.0.5 on 2022-07-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UniQInvoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('item_description', models.CharField(max_length=250)),
                ('model_name', models.CharField(max_length=250)),
                ('manufecture_date', models.DateField()),
                ('receiving_data', models.DateField()),
                ('DP_price', models.IntegerField()),
                ('MRP', models.IntegerField()),
                ('Battery_type', models.CharField(max_length=250)),
                ('Ampear', models.CharField(max_length=250)),
                ('Quantity', models.IntegerField(default=0)),
                ('IsDeleted', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=250)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=250)),
                ('ModifiedDate', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=250)),
                ('warehouse_address', models.CharField(max_length=250)),
                ('IsDeleted', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=250)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=250)),
                ('ModifiedDate', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.CreateModel(
            name='User_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=250)),
                ('Last_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('email_address', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('IsDeleted', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=250)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=250)),
                ('ModifiedDate', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Arrving_Date', models.DateField()),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.item_master')),
                ('Warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.warehouse_master')),
            ],
        ),
        migrations.AddField(
            model_name='item_master',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.warehouse_master'),
        ),
    ]
