# Generated by Django 4.0.5 on 2022-09-12 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UniQInvoice', '0003_alter_company_master_office_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='INVOICE_MASTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.CharField(max_length=250)),
                ('InvoiceDate', models.DateField()),
                ('InvoiceDueDate', models.DateField()),
                ('TotalAmount', models.CharField(max_length=10)),
                ('DueAmount', models.CharField(max_length=10)),
                ('PoNumber', models.CharField(max_length=50)),
                ('TotalTax', models.CharField(max_length=50)),
                ('TaxAmount', models.CharField(max_length=50)),
                ('SubTotal', models.CharField(max_length=50)),
                ('IsDeleted', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=50)),
                ('ModifiedDate', models.DateField()),
                ('DealerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.dealer_master')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('vehicle_type', models.CharField(max_length=250)),
                ('item_description', models.CharField(max_length=250)),
                ('model_name', models.CharField(max_length=250)),
                ('manufecture_date', models.DateField()),
                ('receiving_data', models.DateField()),
                ('DP_price', models.IntegerField()),
                ('MRP', models.IntegerField()),
                ('Battery_type', models.CharField(max_length=250)),
                ('Ampear', models.CharField(max_length=250)),
                ('Quantity', models.IntegerField(default=0)),
                ('IsDeleted', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=250)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=250)),
                ('ModifiedDate', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=250)),
                ('warehouse_address', models.CharField(max_length=250)),
                ('IsDeleted', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=250)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=250)),
                ('ModifiedDate', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.CreateModel(
            name='User_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=250)),
                ('Last_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('email_address', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('IsDeleted', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=250)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=250)),
                ('ModifiedDate', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Arrving_Date', models.DateField()),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.item_master')),
                ('Warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.warehouse_master')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.CreateModel(
            name='POMASTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PoNumber', models.CharField(max_length=20)),
                ('PoDate', models.DateField()),
                ('PoTotalAmount', models.CharField(max_length=10)),
                ('GST', models.CharField(default=0, max_length=10)),
                ('IsDeleted', models.IntegerField()),
                ('Dealer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.dealer_master')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.CreateModel(
            name='PODETAILSMASTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QTY', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('IsDeleted', models.IntegerField()),
                ('ItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.item_master')),
                ('PO_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.pomaster')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENT_STATUS_MASTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(default='PENDING', max_length=200)),
                ('Total_Amount', models.CharField(max_length=10)),
                ('Received_Amount', models.CharField(max_length=10)),
                ('Full_Payment_Received_Date', models.DateField()),
                ('IsDeleted', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('Invoice_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.invoice_master')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENT_MASTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Id', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('Payment_Date', models.DateField()),
                ('IsDeleted', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('Dealer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.dealer_master')),
                ('Invoice_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.invoice_master')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.AddField(
            model_name='item_master',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.warehouse_master'),
        ),
        migrations.CreateModel(
            name='INVOICE_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(null=True)),
                ('Rate', models.CharField(max_length=50, null=True)),
                ('ItemServiceNo', models.IntegerField(null=True)),
                ('IsDeleted', models.IntegerField()),
                ('Invoiceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.invoice_master')),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.item_master')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
    ]
