# Generated by Django 4.0.5 on 2022-09-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomaster',
            old_name='GST',
            new_name='GSTTax',
        ),
        migrations.AddField(
            model_name='pomaster',
            name='SubTotal',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pomaster',
            name='TaxAmount',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
