# Generated by Django 4.0.5 on 2022-08-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_master',
            options={'ordering': ('CreatedDate',)},
        ),
    ]
