# Generated by Django 4.0.5 on 2022-09-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMaster', '0002_rename_gst_pomaster_gsttax_pomaster_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podetailsmaster',
            name='IsDeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pomaster',
            name='IsDeleted',
            field=models.IntegerField(default=0),
        ),
    ]
