# Generated by Django 4.0.5 on 2022-08-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMaster', '0002_alter_item_master_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_master',
            options={},
        ),
        migrations.AddField(
            model_name='item_master',
            name='vehicle_type',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
