# Generated by Django 4.0.5 on 2022-09-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniQInvoice', '0003_alter_company_master_office_number_and_more'),
        ('ItemMaster', '0003_alter_podetailsmaster_isdeleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CREDITNOTE_MASTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditnumber', models.CharField(max_length=50)),
                ('CreditNoteDate', models.DateField()),
                ('CreditNoteAmount', models.CharField(max_length=50)),
                ('IsDeleted', models.IntegerField()),
                ('IsCancel', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=50)),
                ('ModifiedDate', models.DateField()),
                ('DealerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.dealer_master')),
                ('Invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.invoice_master')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.CreateModel(
            name='CREDITNOTE_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(null=True)),
                ('Rate', models.CharField(max_length=50, null=True)),
                ('ItemServiceNo', models.IntegerField(null=True)),
                ('IsDeleted', models.IntegerField()),
                ('Invoiceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.invoice_master')),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.item_master')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
                ('creditid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.creditnote_master')),
            ],
        ),
    ]
