# Generated by Django 4.0.5 on 2022-08-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMaster', '0005_payment_status_master_payment_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_master',
            name='Payment_Type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
