# Generated by Django 4.0.5 on 2022-08-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMaster', '0006_payment_master_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_master',
            name='Payment_Type',
        ),
    ]
