# Generated by Django 4.0.5 on 2022-08-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMaster', '0007_remove_payment_master_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_master',
            name='DueAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
