# Generated by Django 4.0.5 on 2022-08-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMaster', '0008_invoice_master_dueamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_master',
            name='CreatedBy',
            field=models.CharField(default=models.IntegerField(), max_length=50),
        ),
    ]
