# Generated by Django 4.0.5 on 2022-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemMaster', '0009_alter_invoice_master_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_master',
            name='CreatedBy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice_master',
            name='DueAmount',
            field=models.IntegerField(default=models.IntegerField()),
        ),
    ]
