# Generated by Django 4.0.5 on 2022-08-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniQInvoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_master',
            name='Office_Number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='Phone_Number',
            field=models.IntegerField(max_length=10),
        ),
    ]
