# Generated by Django 4.0.5 on 2022-08-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniQInvoice', '0002_alter_company_master_office_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_master',
            name='Office_Number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='Phone_Number',
            field=models.CharField(max_length=15),
        ),
    ]
